M48
; DRILL file {KiCad (6.0.10-0)} date 
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-24T11:04:05+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X79.054Y-80.93
X79.054Y-86.71
T2
X74.93Y-73.66
X74.93Y-93.98
X127.0Y-73.66
X127.0Y-93.98
T0
M30
